language: node_js
node_js:
  - "7"
branches:
  only:
  - master
env:
  global:
  - ENCRYPTION_LABEL: 81808ddf186a
cache: yarn
before_install:
- git config --global user.email "travis@weirdx.io"
- git config --global user.name "Travis CI"
script:
- node --version
- ./deploy.sh
after_success: test $TRAVIS_BRANCH = "master" && ./notify.sh
